"""add cascade delete on user foreign keys

Revision ID: 42e1f72622a9
Revises: 8a966bd2adfc
Create Date: 2026-08-26 14:41:22.876730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e1f72622a9'
down_revision: Union[str, Sequence[str], None] = '8a966bd2adfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('listings_user_id_fkey'), 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key(op.f('listings_user_id_fkey'), 'listings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
