"""initial migration

Revision ID: 87b3b2421d7d
Revises: 
Create Date: 2026-09-15 16:25:59.167305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b3b2421d7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('budget', sa.DECIMAL(), nullable=True),
    sa.Column('sleep_schedule', sa.String(), nullable=True),
    sa.Column('cleanliness_level', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('noise_tolerance', sa.String(), nullable=True),
    sa.Column('smoking_habit', sa.Boolean(), nullable=True),
    sa.Column('drinks_alcohol', sa.Boolean(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.Column('guest_frequency', sa.String(), nullable=True),
    sa.Column('work_or_study_schedule', sa.String(), nullable=True),
    sa.Column('personality_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_per_person', sa.DECIMAL(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('nearest_university', sa.String(), nullable=False),
    sa.Column('available_spots', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('preferred_gender', sa.String(), nullable=False),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=True),
    sa.Column('alcohol_allowed', sa.Boolean(), nullable=True),
    sa.Column('religion_preference', sa.String(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_images_id'), 'listing_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_images_id'), table_name='listing_images')
    op.drop_table('listing_images')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
