"""add listing phone number and images

Revision ID: 8a966bd2adfc
Revises: 
Create Date: 2026-08-23 16:30:02.707507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a966bd2adfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_images_id'), 'listing_images', ['id'], unique=False)
    op.add_column('listings', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_foreign_key(None, 'listings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'phone_number')
    op.drop_index(op.f('ix_listing_images_id'), table_name='listing_images')
    op.drop_table('listing_images')
    # ### end Alembic commands ###
