"""add latitude and longitude to listings

Revision ID: cdbad5eed22b
Revises: 42e1f72622a9
Create Date: 2026-09-10 11:44:31.530052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbad5eed22b'
down_revision: Union[str, Sequence[str], None] = '42e1f72622a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    # ### end Alembic commands ###
